//! The Cedar emitter: per `actors` block, one Cedar policy set
//! (`<Block>.cedar`) and one Cedar JSON schema (`<Block>.cedarschema.json`).
//!
//! Mapping contract (each item pinned by a test here or in `tests/`):
//!
//! - **Schema**: namespace = block name. One entity type per actor; an
//!   actor's `extends` becomes `memberOfTypes` pointing at the parent's
//!   fully-qualified type (roots carry no key). One entity type per
//!   capability class, shaped as a `Record` of the class's primitive-typed
//!   stored attributes (`String`/`char` → `String`, `int`/`long`/`short`/
//!   `byte` → `Long`, `float`/`double` → `Double`, `boolean` → `Boolean`).
//!   Refs, containments, enums, datatypes, and derived features are not
//!   attributes. One action per capability; `principalTypes` are the actors
//!   appearing in any grant entry (permit *or* forbid) for the capability,
//!   in actor declaration order — empty when nothing grants it.
//! - **Policies**: one policy per effect entry, IR source order, fully
//!   parenthesized `when { ... }` conditions over `resource.<feature>`.
//!   Conditions are restricted to a decidable subset: literals, bare names
//!   (primitive attributes only), unary/binary operators, parentheses.
//!   Anything else (`let`, `if`, lambdas, collection algebra, `?.`, `?:`,
//!   `null`, list literals, operation calls) is a generate-time error naming
//!   the capability and the construct — Cedar has no null, so silent
//!   mismatches are refused loudly. `cedar { ... }` entries are spliced
//!   verbatim (the author owns that text). `never_both` is not expressible
//!   in Cedar and degrades to an evidence comment line; the driver enforces
//!   it, not the policy set. Delegations degrade the same way: one evidence
//!   comment line each (name, `from -> to`, permit-entry count, then
//!   ` purpose: <P>` when the delegation declares a purpose), after the
//!   `never_both` comments — policies and schema are untouched.
//!
//! Output is deterministic: the schema JSON is emitted with object keys in
//! canonical alphabetical order (immune to serde_json's `preserve_order`
//! feature, which some build graphs enable), and the policy text follows IR
//! order. Policy files end with exactly one newline.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use rex_expr::{Expr, ExprKind, UnOp};
use rex_ir::{
    ActorModel, ActorsDef, ClassDef, Feature, FeatureKind, GrantEffect, Model, PrimitiveType,
    TypeRef,
};

/// Generates Cedar policies and schemas for the actor-policy artifact
/// `actors`, resolving capability classes against the domain `model`.
///
/// This is the pair API: the policy dimension ([`ActorModel`], produced by
/// compiling an `.actor` file or collected from inline blocks) is consumed
/// separately from the domain dimension ([`Model`]). Capability classes are
/// looked up by their resolved, package-qualified [`TypeRef`] across all
/// packages of `model`.
///
/// Returns a map of file name to contents: `<Block>.cedar` and
/// `<Block>.cedarschema.json` per block, in artifact order. An actor
/// artifact without blocks yields an empty map.
pub fn generate(actors: &ActorModel, model: &Model) -> anyhow::Result<BTreeMap<String, String>> {
    let mut files = BTreeMap::new();
    for actors_block in &actors.blocks {
        files.insert(
            format!("{}.cedar", actors_block.name),
            policy_set(actors_block, model)?,
        );
        files.insert(
            format!("{}.cedarschema.json", actors_block.name),
            schema_json(actors_block, model)?,
        );
    }
    Ok(files)
}

/// The inline convenience: wraps every `actors` block of `model` into an
/// [`ActorModel`] and delegates to [`generate`] (the `gen cedar x.mox`
/// path). A model without `actors` blocks yields an empty map.
pub fn generate_for_model(model: &Model) -> anyhow::Result<BTreeMap<String, String>> {
    let mut actors = ActorModel::new();
    for package in &model.packages {
        actors.blocks.extend(package.actors.iter().cloned());
    }
    generate(&actors, model)
}

/// Generates Cedar output for the pair and writes it into `out_dir`.
pub fn generate_to_dir(actors: &ActorModel, model: &Model, out_dir: &Path) -> anyhow::Result<()> {
    let files = generate(actors, model)?;
    for (relative, contents) in &files {
        let path = out_dir.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, contents)?;
    }
    Ok(())
}

/// The two-line banner every generated policy file starts with.
fn banner(block: &str) -> String {
    format!(
        "// generated by rexlang from actors block `{block}` — do not edit\n\
         // default-deny: anything not permitted is forbidden"
    )
}

/// Builds the policy set for one actors block: banner, then one paragraph
/// per grant entry (effect policy or verbatim cedar splice) in IR order,
/// then one evidence comment per `never_both` group, then one evidence
/// comment per delegation in IR order. Ends with exactly one newline.
fn policy_set(actors: &ActorsDef, model: &Model) -> anyhow::Result<String> {
    let namespace = &actors.name;
    let mut paragraphs = vec![banner(namespace)];
    for grant in &actors.grants {
        for entry in &grant.entries {
            match &entry.cedar {
                Some(text) => paragraphs.push(text.clone()),
                None => {
                    let class = capability_class(actors, model, &entry.capability)?;
                    let mut paragraph = String::new();
                    // One `@obligation` annotation per policy: Cedar
                    // annotations carry exactly one string value and reject
                    // duplicate keys, so multiple obligations on one entry
                    // join into a single comma-separated value (names are
                    // identifiers, so no comma can occur).
                    if !entry.obligations.is_empty() {
                        let joined = cedar_string_literal(&entry.obligations.join(","));
                        paragraph.push_str(&format!("@obligation({joined})\n"));
                    }
                    paragraph.push_str(&format!(
                        "{effect}(principal is {namespace}::{actor}, action == \
                         {namespace}::Action::{capability}, resource is \
                         {namespace}::{class})",
                        effect = match entry.effect {
                            GrantEffect::Permit => "permit",
                            GrantEffect::Forbid => "forbid",
                        },
                        actor = grant.actor,
                        capability = cedar_string_literal(&entry.capability),
                        class = class.name,
                    ));
                    if let Some(when) = &entry.when {
                        paragraph.push_str(&format!(
                            " when {{ {} }}",
                            condition_text(&entry.capability, class, when)?
                        ));
                    }
                    paragraph.push(';');
                    paragraphs.push(paragraph);
                }
            }
        }
    }
    for constraint in &actors.never_both {
        paragraphs.push(format!(
            "// never_both: {}",
            constraint.capabilities.join(", ")
        ));
    }
    // Delegations are evidence comments only: like `never_both`, the driver
    // enforces them at compile time and the authorization gateway enforces
    // them at runtime, so neither policies nor schema change. The count is
    // the number of permit entries — what the gateway would grant. A
    // declared purpose appends ` purpose: <P>`; without one the line ends
    // right after the count.
    for delegation in &actors.delegations {
        let permits = delegation
            .entries
            .iter()
            .filter(|entry| entry.effect == GrantEffect::Permit)
            .count();
        let mut line = format!(
            "// delegation {}: {} -> {} ({} capabilities)",
            delegation.name, delegation.from, delegation.to, permits
        );
        if let Some(purpose) = &delegation.purpose {
            line.push_str(&format!(" purpose: {purpose}"));
        }
        paragraphs.push(line);
    }
    let mut out = paragraphs.join("\n\n");
    out.push('\n');
    Ok(out)
}

/// Builds the Cedar JSON schema for one actors block.
fn schema_json(actors: &ActorsDef, model: &Model) -> anyhow::Result<String> {
    let namespace = &actors.name;
    let mut entity_types = serde_json::Map::new();
    for actor in &actors.actors {
        let mut definition = serde_json::Map::new();
        if let Some(parent) = &actor.extends {
            definition.insert(
                "memberOfTypes".to_string(),
                serde_json::json!([format!("{namespace}::{parent}")]),
            );
        }
        entity_types.insert(actor.name.clone(), serde_json::Value::Object(definition));
    }
    let mut seen_classes = BTreeSet::new();
    for capability in &actors.capabilities {
        let class = capability_class(actors, model, &capability.name)?;
        if !seen_classes.insert(class.name.clone()) {
            continue;
        }
        let mut attributes = serde_json::Map::new();
        for feature in &class.features {
            if let Some(cedar_type) = primitive_cedar_type(feature) {
                attributes.insert(
                    feature.name.clone(),
                    serde_json::json!({"type": cedar_type}),
                );
            }
        }
        entity_types.insert(
            class.name.clone(),
            serde_json::json!({
                "shape": {
                    "type": "Record",
                    "attributes": attributes,
                }
            }),
        );
    }
    let mut actions = serde_json::Map::new();
    for capability in &actors.capabilities {
        let class = capability_class(actors, model, &capability.name)?;
        let principals: Vec<String> = actors
            .actors
            .iter()
            .filter(|actor| block_grants_capability(actors, &actor.name, &capability.name))
            .map(|actor| format!("{namespace}::{}", actor.name))
            .collect();
        actions.insert(
            capability.name.clone(),
            serde_json::json!({
                "appliesTo": {
                    "principalTypes": principals,
                    "resourceTypes": [format!("{namespace}::{}", class.name)],
                    "context": {
                        "type": "Record",
                        "attributes": {},
                    },
                }
            }),
        );
    }
    let mut namespace_document = serde_json::Map::new();
    namespace_document.insert(
        "entityTypes".to_string(),
        serde_json::Value::Object(entity_types),
    );
    namespace_document.insert("actions".to_string(), serde_json::Value::Object(actions));
    let mut root = serde_json::Map::new();
    root.insert(
        namespace.clone(),
        serde_json::Value::Object(namespace_document),
    );
    Ok(serde_json::to_string_pretty(&canonical_key_order(
        serde_json::Value::Object(root),
    ))?)
}

/// Recursively re-inserts object keys in alphabetical order, so the emitted
/// bytes are pinned no matter which key order `serde_json::Map` uses (it is
/// a `BTreeMap` unless some crate in the build graph enables the
/// `preserve_order` feature, which flips it to insertion order).
fn canonical_key_order(value: serde_json::Value) -> serde_json::Value {
    match value {
        serde_json::Value::Object(map) => {
            let mut entries: Vec<(String, serde_json::Value)> = map.into_iter().collect();
            entries.sort_by(|left, right| left.0.cmp(&right.0));
            entries
                .into_iter()
                .map(|(key, value)| (key, canonical_key_order(value)))
                .collect::<serde_json::Map<String, serde_json::Value>>()
                .into()
        }
        other => other,
    }
}

/// `true` if any grant naming `actor` carries an effect entry (permit or
/// forbid) on `capability`. Verbatim cedar entries never contribute.
fn block_grants_capability(actors: &ActorsDef, actor: &str, capability: &str) -> bool {
    actors.grants.iter().any(|grant| {
        grant.actor == actor
            && grant
                .entries
                .iter()
                .any(|entry| entry.cedar.is_none() && entry.capability == capability)
    })
}

/// The class definition a capability of `actors` is granted on, resolved
/// through the capability's package-qualified `TypeRef`.
fn capability_class<'a>(
    actors: &ActorsDef,
    model: &'a Model,
    capability: &str,
) -> anyhow::Result<&'a ClassDef> {
    let TypeRef::Class {
        package,
        name: class,
    } = actors
        .capabilities
        .iter()
        .find(|candidate| candidate.name == capability)
        .map(|capability| &capability.class)
        .ok_or_else(|| anyhow::anyhow!("unknown capability `{capability}`"))?
    else {
        anyhow::bail!(
            "capability `{capability}` must be granted on a class, which the \
             driver validates"
        );
    };
    model
        .packages
        .iter()
        .find(|candidate| candidate.name == *package)
        .and_then(|package| {
            package
                .classes
                .iter()
                .find(|candidate| candidate.name == *class)
        })
        .ok_or_else(|| {
            anyhow::anyhow!(
                "capability `{capability}` is granted on class `{class}`, which is \
                 not in the model"
            )
        })
}

/// The Cedar type of a primitive-typed stored attribute, or `None` for any
/// feature that is not a primitive attribute (refs, containments, enums,
/// datatypes, derived features).
fn primitive_cedar_type(feature: &Feature) -> Option<&'static str> {
    if feature.is_derived || feature.kind != FeatureKind::Attribute {
        return None;
    }
    let TypeRef::Primitive(primitive) = feature.type_ else {
        return None;
    };
    Some(match primitive {
        // Dates have no Cedar attribute representation: Cedar has no date
        // type, so a date attribute is not a schema attribute and a `when`
        // condition over it is refused by name (`is_primitive_attribute`).
        PrimitiveType::Date => return None,
        PrimitiveType::String | PrimitiveType::Char => "String",
        PrimitiveType::Int | PrimitiveType::Long | PrimitiveType::Short | PrimitiveType::Byte => {
            "Long"
        }
        PrimitiveType::Float | PrimitiveType::Double => "Double",
        PrimitiveType::Boolean => "Boolean",
    })
}

/// `true` if `name` is a primitive-typed stored attribute of `class`.
fn is_primitive_attribute(class: &ClassDef, name: &str) -> bool {
    class
        .features
        .iter()
        .any(|feature| feature.name == name && primitive_cedar_type(feature).is_some())
}

/// Parses a stored `when` condition and renders it as a Cedar `when { ... }`
/// clause body (the braces themselves are added by the caller).
fn condition_text(capability: &str, class: &ClassDef, source: &str) -> anyhow::Result<String> {
    let parsed = rex_expr::parse(source);
    match parsed.ast {
        Some(ast) if parsed.errors.is_empty() => emit_condition(&ast, capability, class),
        _ => anyhow::bail!(
            "capability `{capability}`: `when` condition is not valid rexlang \
             syntax; the driver must have rejected it"
        ),
    }
}

/// Renders one condition expression as fully parenthesized Cedar, refusing
/// every construct outside the decidable subset.
fn emit_condition(expr: &Expr, capability: &str, class: &ClassDef) -> anyhow::Result<String> {
    let reject = |construct: &str| {
        anyhow::anyhow!(
            "capability `{capability}`: `when` condition uses {construct}, \
             which has no Cedar mapping"
        )
    };
    match &expr.kind {
        ExprKind::Int(value) => Ok(value.to_string()),
        ExprKind::String(text) => Ok(cedar_string_literal(text)),
        ExprKind::Bool(value) => Ok(value.to_string()),
        ExprKind::Null => Err(reject("`null`")),
        ExprKind::Name(name) => {
            if is_primitive_attribute(class, name) {
                Ok(format!("resource.{name}"))
            } else {
                Err(anyhow::anyhow!(
                    "capability `{capability}`: `when` condition references \
                     `{name}`, which is not a primitive attribute of `{}`",
                    class.name
                ))
            }
        }
        ExprKind::Unary { op, expr } => {
            let inner = emit_condition(expr, capability, class)?;
            Ok(match op {
                UnOp::Not => format!("!({inner})"),
                UnOp::Neg => format!("-({inner})"),
            })
        }
        ExprKind::Binary { op, lhs, rhs } => Ok(format!(
            "({} {op} {})",
            emit_condition(lhs, capability, class)?,
            emit_condition(rhs, capability, class)?
        )),
        ExprKind::FeatureAccess {
            receiver,
            name,
            optional_safe,
        } => {
            if *optional_safe {
                return Err(reject("`?.`"));
            }
            let receiver = emit_condition(receiver, capability, class)?;
            Ok(format!("{receiver}.{}", name.value))
        }
        ExprKind::Coalesce { .. } => Err(reject("`?:`")),
        ExprKind::Call { .. } => Err(reject("an operation call")),
        ExprKind::Algebra { kind, .. } => Err(reject(&format!("collection algebra `{kind}`"))),
        ExprKind::If { .. } => Err(reject("`if`")),
        ExprKind::Let { .. } => Err(reject("`let`")),
        ExprKind::Lambda { .. } => Err(reject("a lambda")),
        ExprKind::ListLiteral(_) => Err(reject("list literals")),
    }
}

/// Renders `text` as a Cedar string literal, escaping backslashes and
/// quotes.
fn cedar_string_literal(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(character),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use rex_ir::{
        ActorDef, ActorModel, CapabilityDef, DelegationDef, GrantDef, GrantEntry, Multiplicity,
        NeverBothDef, Package,
    };

    fn attribute(name: &str, primitive: PrimitiveType) -> Feature {
        Feature::new(
            name,
            FeatureKind::Attribute,
            TypeRef::Primitive(primitive),
            Multiplicity::REQUIRED,
        )
    }

    fn class_ref(package: &str, name: &str) -> TypeRef {
        TypeRef::Class {
            package: package.to_string(),
            name: name.to_string(),
        }
    }

    /// `class <name> { <features> }`.
    fn class(name: &str, features: Vec<Feature>) -> ClassDef {
        ClassDef::new(name, vec![], features)
    }

    /// The fixture block `Support`: Customer / Agent extends Customer /
    /// Manager, ReadTicket + RaiseRefund on Ticket, plus the given grants.
    fn fixture_actors(grants: Vec<GrantDef>) -> ActorsDef {
        let mut actors = ActorsDef::new("Support");
        for name in ["Customer", "Agent", "Manager"] {
            actors = actors.actor(ActorDef::new(name));
        }
        actors.actors[1] = ActorDef::new("Agent").extends("Customer");
        for name in ["ReadTicket", "RaiseRefund"] {
            actors = actors.capability(CapabilityDef::new(name, class_ref("demo", "Ticket")));
        }
        for grant in grants {
            actors = actors.grant(grant);
        }
        actors
    }

    /// A pair over `Ticket { id: String, title: String, internal: boolean,
    /// amount: int, refers User assignee, derived fee: double }`: the actors
    /// block lives only in the [`ActorModel`] dimension; the domain model
    /// carries the classes (no inline actors at all).
    fn fixture_pair(actors: ActorsDef) -> (ActorModel, Model) {
        let mut ticket = class(
            "Ticket",
            vec![
                attribute("id", PrimitiveType::String),
                attribute("title", PrimitiveType::String),
                attribute("internal", PrimitiveType::Boolean),
                attribute("amount", PrimitiveType::Int),
            ],
        );
        ticket.features.push(Feature::new(
            "assignee",
            FeatureKind::CrossReference,
            class_ref("demo", "User"),
            Multiplicity::OPTIONAL,
        ));
        ticket.features.push(
            Feature::new(
                "fee",
                FeatureKind::Attribute,
                TypeRef::Primitive(PrimitiveType::Double),
                Multiplicity::OPTIONAL,
            )
            .derived(),
        );
        let mut model = Model::new();
        let mut package = Package::new("demo");
        package.classes = vec![ticket];
        model.packages.push(package);
        (ActorModel::new().block(actors), model)
    }

    fn grant(actor: &str, entries: Vec<GrantEntry>) -> GrantDef {
        let mut grant = GrantDef::new(actor);
        for entry in entries {
            grant = grant.entry(entry);
        }
        grant
    }

    /// `<delegation <name>: from -> to { entries }>`.
    fn delegation(name: &str, from: &str, to: &str, entries: Vec<GrantEntry>) -> DelegationDef {
        let mut delegation = DelegationDef::new(name, from, to);
        for entry in entries {
            delegation = delegation.entry(entry);
        }
        delegation
    }

    /// Generates and returns the `<Block>.cedar` contents.
    fn cedar_of(pair: &(ActorModel, Model)) -> String {
        generate(&pair.0, &pair.1)
            .expect("generate")
            .remove("Support.cedar")
            .expect("policies file")
    }

    /// Generates and returns the schema JSON as parsed JSON.
    fn schema_of(pair: &(ActorModel, Model)) -> serde_json::Value {
        let files = generate(&pair.0, &pair.1).expect("generate");
        let schema = files.get("Support.cedarschema.json").expect("schema file");
        serde_json::from_str(schema).expect("valid JSON")
    }

    // -- schema mapping ------------------------------------------------------

    #[test]
    fn primitive_types_map_to_cedar_types() {
        let mut actors = ActorsDef::new("N");
        actors = actors.actor(ActorDef::new("A"));
        actors = actors.capability(CapabilityDef::new("Cap", class_ref("demo", "Wide")));
        let mut model = Model::new();
        let mut package = Package::new("demo");
        package.classes = vec![class(
            "Wide",
            vec![
                attribute("s", PrimitiveType::String),
                attribute("c", PrimitiveType::Char),
                attribute("i", PrimitiveType::Int),
                attribute("l", PrimitiveType::Long),
                attribute("sh", PrimitiveType::Short),
                attribute("b", PrimitiveType::Byte),
                attribute("f", PrimitiveType::Float),
                attribute("d", PrimitiveType::Double),
                attribute("bo", PrimitiveType::Boolean),
            ],
        )];
        model.packages.push(package);
        let actors = ActorModel::new().block(actors);
        let files = generate(&actors, &model).expect("generate");
        let schema: serde_json::Value =
            serde_json::from_str(files.get("N.cedarschema.json").expect("schema")).expect("json");
        let attributes = &schema["N"]["entityTypes"]["Wide"]["shape"]["attributes"];
        assert_eq!(attributes["s"], serde_json::json!({"type": "String"}));
        assert_eq!(attributes["c"], serde_json::json!({"type": "String"}));
        assert_eq!(attributes["i"], serde_json::json!({"type": "Long"}));
        assert_eq!(attributes["l"], serde_json::json!({"type": "Long"}));
        assert_eq!(attributes["sh"], serde_json::json!({"type": "Long"}));
        assert_eq!(attributes["b"], serde_json::json!({"type": "Long"}));
        assert_eq!(attributes["f"], serde_json::json!({"type": "Double"}));
        assert_eq!(attributes["d"], serde_json::json!({"type": "Double"}));
        assert_eq!(attributes["bo"], serde_json::json!({"type": "Boolean"}));
    }

    #[test]
    fn date_attributes_have_no_cedar_representation() {
        // Cedar has no date type: a date attribute is not a schema
        // attribute, so a `when` condition over it is refused by name (see
        // the policy-mapping refusals below).
        let mut actors = ActorsDef::new("N");
        actors = actors.actor(ActorDef::new("A"));
        actors = actors.capability(CapabilityDef::new("Cap", class_ref("demo", "Timed")));
        let mut model = Model::new();
        let mut package = Package::new("demo");
        package.classes = vec![class(
            "Timed",
            vec![
                attribute("dueDate", PrimitiveType::Date),
                attribute("s", PrimitiveType::String),
            ],
        )];
        model.packages.push(package);
        let actors = ActorModel::new().block(actors);
        let files = generate(&actors, &model).expect("generate");
        let schema: serde_json::Value =
            serde_json::from_str(files.get("N.cedarschema.json").expect("schema")).expect("json");
        let attributes = &schema["N"]["entityTypes"]["Timed"]["shape"]["attributes"];
        assert_eq!(
            attributes
                .as_object()
                .expect("attributes")
                .keys()
                .collect::<Vec<_>>(),
            ["s"],
            "the date attribute is omitted from the Cedar schema"
        );
    }

    #[test]
    fn non_primitive_features_are_not_schema_attributes() {
        let pair = fixture_pair(fixture_actors(vec![]));
        let schema = schema_of(&pair);
        let attributes = &schema["Support"]["entityTypes"]["Ticket"]["shape"]["attributes"];
        assert_eq!(
            attributes
                .as_object()
                .expect("attributes")
                .keys()
                .collect::<Vec<_>>(),
            ["amount", "id", "internal", "title"],
            "canonical key order; ref + derived features are excluded"
        );
    }

    #[test]
    fn actor_extends_becomes_member_of_types_and_roots_have_none() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )]);
        let schema = schema_of(&fixture_pair(actors));
        let entity_types = &schema["Support"]["entityTypes"];
        assert_eq!(
            entity_types["Agent"],
            serde_json::json!({"memberOfTypes": ["Support::Customer"]})
        );
        assert_eq!(entity_types["Customer"], serde_json::json!({}));
        assert!(
            entity_types["Customer"].get("memberOfTypes").is_none(),
            "roots carry no memberOfTypes key"
        );
    }

    #[test]
    fn principal_types_follow_actor_declaration_order_and_count_forbids() {
        // Grants appear in reverse declaration order; the forbid on Manager
        // must still place Manager after Customer (declaration order), and
        // Agent, granted nothing on ReadTicket, is omitted.
        let actors = fixture_actors(vec![
            grant("Manager", vec![GrantEntry::forbid("ReadTicket")]),
            grant("Customer", vec![GrantEntry::permit("ReadTicket")]),
        ]);
        let schema = schema_of(&fixture_pair(actors));
        let applies_to = &schema["Support"]["actions"]["ReadTicket"]["appliesTo"];
        assert_eq!(
            applies_to["principalTypes"],
            serde_json::json!(["Support::Customer", "Support::Manager"]),
            "declaration order, forbid counts, non-granting actor omitted"
        );
        assert_eq!(
            applies_to["resourceTypes"],
            serde_json::json!(["Support::Ticket"])
        );
        assert_eq!(
            applies_to["context"],
            serde_json::json!({"type": "Record", "attributes": {}})
        );
    }

    #[test]
    fn capability_without_grants_gets_empty_principal_types() {
        let schema = schema_of(&fixture_pair(fixture_actors(vec![])));
        assert_eq!(
            schema["Support"]["actions"]["RaiseRefund"]["appliesTo"]["principalTypes"],
            serde_json::json!([]),
            "no grant mentions RaiseRefund"
        );
    }

    #[test]
    fn multiple_blocks_emit_one_pair_each_in_ir_order() {
        let (mut actors, model) = fixture_pair(fixture_actors(vec![]));
        let mut second = ActorsDef::new("Billing");
        second = second.actor(ActorDef::new("Clerk"));
        actors.blocks.push(second);
        let files = generate(&actors, &model).expect("generate");
        assert_eq!(
            files.keys().collect::<Vec<_>>(),
            [
                "Billing.cedar",
                "Billing.cedarschema.json",
                "Support.cedar",
                "Support.cedarschema.json"
            ]
        );
    }

    // -- pair API -------------------------------------------------------------

    #[test]
    fn empty_actor_model_yields_an_empty_map() {
        let (_, model) = fixture_pair(fixture_actors(vec![]));
        let empty = ActorModel::new();
        let files = generate(&empty, &model).expect("generate");
        assert!(files.is_empty(), "got: {:?}", files.keys());
    }

    #[test]
    fn blocks_and_classes_live_in_different_packages_of_the_pair() {
        // The payoff surface: the actors block references its capability
        // class through a package-qualified TypeRef, and the class is found
        // in the domain model even though the block itself is in no package
        // of that model at all.
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )]);
        let pair = fixture_pair(actors);
        let files = generate(&pair.0, &pair.1).expect("generate");
        assert_eq!(files.keys().len(), 2);
        assert!(files["Support.cedar"].contains("resource is Support::Ticket)"));
    }

    #[test]
    fn generate_for_model_wraps_inline_blocks_and_matches_the_pair_call() {
        // The `gen cedar x.mox` path: a model with inline `actors` blocks
        // produces exactly what the explicit pair call produces.
        let mut actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )]);
        actors.capabilities[0].class = class_ref("demo", "Ticket");
        let mut model = Model::new();
        let mut package = Package::new("demo");
        package.classes = vec![class(
            "Ticket",
            vec![attribute("id", PrimitiveType::String)],
        )];
        package.actors = vec![actors.clone()];
        model.packages.push(package);

        let via_model = generate_for_model(&model).expect("generate_for_model");
        let via_pair = generate(&ActorModel::new().block(actors), &model).expect("generate");
        assert_eq!(via_model, via_pair);
        assert_eq!(via_model.keys().len(), 2);
    }

    // -- policy mapping ------------------------------------------------------

    #[test]
    fn banner_and_never_both_comment_lines_are_pinned() {
        let mut actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )]);
        actors = actors.never_both(NeverBothDef::new("ReadTicket", "RaiseRefund"));
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.starts_with(
                "// generated by rexlang from actors block `Support` — do not edit\n\
                 // default-deny: anything not permitted is forbidden\n\n"
            ),
            "banner: {cedar}"
        );
        assert!(
            cedar.ends_with("// never_both: ReadTicket, RaiseRefund\n"),
            "trailing comment: {cedar}"
        );
    }

    #[test]
    fn effect_policy_line_shape_is_pinned() {
        let actors = fixture_actors(vec![grant(
            "Agent",
            vec![GrantEntry::forbid("RaiseRefund")],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains(
                "forbid(principal is Support::Agent, action == \
                 Support::Action::\"RaiseRefund\", resource is Support::Ticket);"
            ),
            "policy line: {cedar}"
        );
    }

    #[test]
    fn obligations_become_annotation_lines_above_the_policy() {
        let actors = fixture_actors(vec![grant(
            "Agent",
            vec![GrantEntry::permit("RaiseRefund")
                .obligation("audit")
                .obligation("four-eyes")],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains(
                "@obligation(\"audit,four-eyes\")\npermit(\
                 principal is Support::Agent"
            ),
            "multiple obligations join one annotation value (Cedar rejects \
             duplicate annotation keys): {cedar}"
        );
    }

    #[test]
    fn a_single_obligation_stays_a_bare_annotation() {
        let actors = fixture_actors(vec![grant(
            "Agent",
            vec![GrantEntry::permit("RaiseRefund").obligation("audit")],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains("@obligation(\"audit\")\npermit(principal is Support::Agent"),
            "single obligation: {cedar}"
        );
    }

    #[test]
    fn when_conditions_map_names_and_ops_fully_parenthesized() {
        let actors = fixture_actors(vec![grant(
            "Agent",
            vec![GrantEntry::permit("RaiseRefund")
                .when("(!(internal) && amount <= 1000) || title == \"a \\ b\"")],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains(
                "when { ((!(resource.internal) && (resource.amount <= 1000)) \
                 || (resource.title == \"a \\\\ b\")) };"
            ),
            "condition: {cedar}"
        );
    }

    #[test]
    fn rejected_constructs_name_the_capability_and_the_construct() {
        let rejected: [(&str, &str); 8] = [
            ("let x = 1; x", "`let`"),
            ("if internal { 1 } else { 2 }", "`if`"),
            ("internal?.flag == true", "`?.`"),
            ("internal ?: true", "`?:`"),
            ("internal == null", "`null`"),
            ("internal.filter(x => x)", "collection algebra `filter`"),
            ("x => x", "a lambda"),
            ("[1, 2]", "list literals"),
        ];
        for (source, construct) in rejected {
            let actors = fixture_actors(vec![grant(
                "Agent",
                vec![GrantEntry::permit("RaiseRefund").when(source)],
            )]);
            let pair = fixture_pair(actors);
            let error = generate(&pair.0, &pair.1).expect_err("must be rejected");
            assert_eq!(
                error.to_string(),
                format!(
                    "capability `RaiseRefund`: `when` condition uses {construct}, \
                     which has no Cedar mapping"
                ),
                "source: {source}"
            );
        }
    }

    #[test]
    fn condition_over_non_primitive_attribute_is_an_error() {
        let actors = fixture_actors(vec![grant(
            "Agent",
            vec![GrantEntry::permit("RaiseRefund").when("assignee != null")],
        )]);
        let pair = fixture_pair(actors);
        let error = generate(&pair.0, &pair.1).expect_err("must be rejected");
        assert_eq!(
            error.to_string(),
            "capability `RaiseRefund`: `when` condition references `assignee`, \
             which is not a primitive attribute of `Ticket`"
        );
    }

    #[test]
    fn cedar_entries_are_spliced_verbatim_as_their_own_paragraph() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![
                GrantEntry::permit("ReadTicket"),
                GrantEntry::permit("").cedar("permit(principal, action, resource);"),
                GrantEntry::forbid("RaiseRefund"),
            ],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains(
                ";\n\npermit(principal, action, resource);\n\nforbid(\
                 principal is Support::Customer"
            ),
            "splice sits between the two policies as its own paragraph: {cedar}"
        );
    }

    #[test]
    fn policy_files_end_with_exactly_one_newline() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(cedar.ends_with('\n'));
        assert!(!cedar.ends_with("\n\n"), "exactly one trailing newline");
    }

    // -- delegation evidence --------------------------------------------------

    #[test]
    fn a_block_without_delegations_keeps_its_exact_shape() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )]);
        let cedar = cedar_of(&fixture_pair(actors));
        assert_eq!(
            cedar,
            "// generated by rexlang from actors block `Support` — do not edit\n\
             // default-deny: anything not permitted is forbidden\n\
             \n\
             permit(principal is Support::Customer, action == \
             Support::Action::\"ReadTicket\", resource is Support::Ticket);\n",
            "no delegation evidence may appear when the block has none"
        );
    }

    #[test]
    fn delegation_evidence_comment_is_pinned_byte_for_byte() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )])
        .delegation(delegation(
            "CustomerToAgent",
            "Customer",
            "Agent",
            vec![
                GrantEntry::permit("ReadTicket"),
                GrantEntry::permit("RaiseRefund"),
            ],
        ));
        let cedar = cedar_of(&fixture_pair(actors));
        assert_eq!(
            cedar,
            "// generated by rexlang from actors block `Support` — do not edit\n\
             // default-deny: anything not permitted is forbidden\n\
             \n\
             permit(principal is Support::Customer, action == \
             Support::Action::\"ReadTicket\", resource is Support::Ticket);\n\
             \n\
             // delegation CustomerToAgent: Customer -> Agent (2 capabilities)\n",
            "delegations are evidence comments only; policies stay unchanged"
        );
    }

    #[test]
    fn delegations_emit_one_evidence_line_each_in_ir_order() {
        let actors = fixture_actors(vec![])
            .delegation(delegation(
                "FrontDesk",
                "Customer",
                "Agent",
                vec![GrantEntry::permit("ReadTicket")],
            ))
            .delegation(delegation(
                "Escalation",
                "Manager",
                "Agent",
                vec![GrantEntry::permit("RaiseRefund")],
            ));
        let cedar = cedar_of(&fixture_pair(actors));
        assert_eq!(
            cedar,
            "// generated by rexlang from actors block `Support` — do not edit\n\
             // default-deny: anything not permitted is forbidden\n\
             \n\
             // delegation FrontDesk: Customer -> Agent (1 capabilities)\n\
             \n\
             // delegation Escalation: Manager -> Agent (1 capabilities)\n"
        );
    }

    #[test]
    fn delegation_count_only_counts_permit_entries() {
        let actors = fixture_actors(vec![]).delegation(delegation(
            "Mixed",
            "Customer",
            "Agent",
            vec![
                GrantEntry::forbid("RaiseRefund"),
                GrantEntry::permit("ReadTicket"),
                GrantEntry::permit("RaiseRefund"),
                GrantEntry::forbid("ReadTicket"),
            ],
        ));
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains("// delegation Mixed: Customer -> Agent (2 capabilities)\n"),
            "forbid entries never count toward the total: {cedar}"
        );
    }

    #[test]
    fn zero_permit_delegations_still_emit_the_comment() {
        let actors = fixture_actors(vec![])
            .delegation(delegation(
                "OnlyForbids",
                "Customer",
                "Agent",
                vec![GrantEntry::forbid("RaiseRefund")],
            ))
            .delegation(delegation("NoEntries", "Manager", "Agent", vec![]));
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.contains("// delegation OnlyForbids: Customer -> Agent (0 capabilities)\n"),
            "forbid-only delegation: {cedar}"
        );
        assert!(
            cedar.contains("// delegation NoEntries: Manager -> Agent (0 capabilities)\n"),
            "empty delegation: {cedar}"
        );
    }

    #[test]
    fn delegation_comments_follow_the_never_both_comment() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )])
        .never_both(NeverBothDef::new("ReadTicket", "RaiseRefund"))
        .delegation(delegation(
            "SupportHelp",
            "Customer",
            "Agent",
            vec![GrantEntry::permit("ReadTicket")],
        ));
        let cedar = cedar_of(&fixture_pair(actors));
        assert!(
            cedar.ends_with(
                "// never_both: ReadTicket, RaiseRefund\n\
                 \n\
                 // delegation SupportHelp: Customer -> Agent (1 capabilities)\n"
            ),
            "delegation evidence trails the never_both evidence: {cedar}"
        );
    }

    #[test]
    fn delegation_with_purpose_pins_the_purpose_suffix() {
        let actors = fixture_actors(vec![grant(
            "Customer",
            vec![GrantEntry::permit("ReadTicket")],
        )])
        .delegation(
            delegation(
                "CustomerToAgent",
                "Customer",
                "Agent",
                vec![
                    GrantEntry::permit("ReadTicket"),
                    GrantEntry::permit("RaiseRefund"),
                ],
            )
            .purpose("seasonal support surge"),
        );
        let cedar = cedar_of(&fixture_pair(actors));
        assert_eq!(
            cedar,
            "// generated by rexlang from actors block `Support` — do not edit\n\
             // default-deny: anything not permitted is forbidden\n\
             \n\
             permit(principal is Support::Customer, action == \
             Support::Action::\"ReadTicket\", resource is Support::Ticket);\n\
             \n\
             // delegation CustomerToAgent: Customer -> Agent \
             (2 capabilities) purpose: seasonal support surge\n",
            "a declared purpose appends exactly ` purpose: <P>` to the \
             evidence line; nothing else changes"
        );
    }

    #[test]
    fn delegation_without_purpose_keeps_the_pre_feature_byte_format() {
        let actors = fixture_actors(vec![]).delegation(delegation(
            "Plain",
            "Customer",
            "Agent",
            vec![GrantEntry::permit("ReadTicket")],
        ));
        let cedar = cedar_of(&fixture_pair(actors));
        assert_eq!(
            cedar,
            "// generated by rexlang from actors block `Support` — do not edit\n\
             // default-deny: anything not permitted is forbidden\n\
             \n\
             // delegation Plain: Customer -> Agent (1 capabilities)\n",
            "no purpose: the line ends right after the count, no suffix and \
             no trailing space"
        );
    }

    #[test]
    fn mixed_purpose_delegations_keep_each_line_correct_in_ir_order() {
        let actors = fixture_actors(vec![])
            .delegation(
                delegation(
                    "FrontDesk",
                    "Customer",
                    "Agent",
                    vec![GrantEntry::permit("ReadTicket")],
                )
                .purpose("front desk coverage"),
            )
            .delegation(delegation(
                "Escalation",
                "Manager",
                "Agent",
                vec![GrantEntry::permit("RaiseRefund")],
            ));
        let cedar = cedar_of(&fixture_pair(actors));
        assert_eq!(
            cedar,
            "// generated by rexlang from actors block `Support` — do not edit\n\
             // default-deny: anything not permitted is forbidden\n\
             \n\
             // delegation FrontDesk: Customer -> Agent (1 capabilities) \
             purpose: front desk coverage\n\
             \n\
             // delegation Escalation: Manager -> Agent (1 capabilities)\n",
            "each line carries its own delegation's purpose, in IR order"
        );
    }
}
