[package]
name = "rex-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
rex-syntax = { workspace = true }
rex-ir = { workspace = true }
rex-vocab = { workspace = true }
salsa = { workspace = true }
ariadne = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
