[package]
name = "rex-backend-jsonschema"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rex-ir = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
jsonschema = { workspace = true }
rex-driver = { workspace = true }
